import { StyleSheet } from "react-native";
import { Theme } from "../theme/theme";

export const createStyles = (theme: Theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    scrollContent: {
        padding: 24,
        paddingBottom: 40,
        gap: 28,
    },
    inputGroup: {
        gap: 10,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        height: 56,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.surface,
    },
    input: {
        flex: 1,
        fontSize: 16,
        height: '100%',
        color: theme.colors.text,
    },
    currency: {
        fontSize: 18,
        fontWeight: '700',
        marginRight: 10,
        color: theme.colors.primary,
    },
    selectText: {
        flex: 1,
        fontSize: 16,
        color: theme.colors.text,
    },
    buttonContainer: {
        marginTop: 12,
    },
    switchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: theme.colors.card,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    switchLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    infoContent: {
        padding: 20,
        gap: 16,
    },
    infoSection: {
        gap: 8,
    },
    infoTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    infoText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
    },
    assetList: {
        backgroundColor: theme.colors.surface,
        borderRadius: 12,
        padding: 12,
        gap: 8,
    },
    assetItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    assetItemText: {
        fontSize: 14,
        color: theme.colors.text,
        fontWeight: '500',
    },
    typeToggle: {
        flexDirection: 'row',
        backgroundColor: theme.colors.backgroundSecondary,
        borderRadius: 16,
        padding: 6,
        gap: 6,
    },
    typeToggleBtn: {
        flex: 1,
        paddingVertical: 14,
        alignItems: 'center',
        borderRadius: 12,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    typeToggleBtnActive: {
        backgroundColor: theme.colors.card,
        ...theme.shadows.small,
    },
    typeToggleText: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    typeToggleTextActive: {
        color: theme.colors.text,
    },
    typeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    typeCard: {
        width: '48%',
        minHeight: 130,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: theme.colors.border,
        backgroundColor: theme.colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 18,
        gap: 10,
    },
    typeCardSelected: {
        borderColor: theme.colors.primary,
        backgroundColor: `${theme.colors.primary}08`,
        ...theme.shadows.small,
    },
    typeCardIcon: {
        width: 52,
        height: 52,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    typeCardLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.colors.text,
    },
    typeCardDesc: {
        fontSize: 10,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        lineHeight: 14,
        paddingHorizontal: 4,
    },
    autoCalcCard: {
        borderRadius: 20,
        padding: 24,
        backgroundColor: theme.colors.card,
        borderWidth: 1,
        borderColor: theme.colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        ...theme.shadows.medium,
    },
    autoCalcLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    autoCalcValue: {
        fontSize: 24,
        fontWeight: '800',
        color: theme.colors.text,
        marginTop: 4,
    },
    autoCalcNote: {
        fontSize: 11,
        color: theme.colors.textTertiary,
        marginTop: 4,
        fontStyle: 'italic',
    },
    sectionSeparator: {
        height: 1,
        backgroundColor: theme.colors.border,
        marginVertical: 4,
    },
});
