import { Platform, StyleSheet } from "react-native";
import type { Theme } from "../theme";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    summaryCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}80`,
      ...theme.shadows.medium,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: theme.spacing.xs + 2,
    },
    summaryLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.textSecondary,
    },
    summaryAmount: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: `${theme.colors.textTertiary}30`,
      marginVertical: theme.spacing.s + 2,
    },
    surplusAmount: {
      fontSize: theme.typography.h2.fontSize,
      fontWeight: "700",
    },
    surplusRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: theme.spacing.s,
    },
    surplusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
    },
    surplusBadgeText: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    section: {
      marginHorizontal: theme.spacing.m,
      marginBottom: theme.spacing.m,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: theme.spacing.s,
      paddingHorizontal: theme.spacing.s,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: theme.colors.textSecondary,
    },
    sectionTotal: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.colors.text,
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: theme.spacing.m,
      borderRadius: 16,
      marginBottom: theme.spacing.s,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
    },
    itemIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.m,
    },
    itemInfo: {
      flex: 1,
    },
    itemLabel: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    itemSubtext: {
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    itemAmount: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "700",
    },
    forecastCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
      ...theme.shadows.small,
    },
    forecastMonth: {
      fontSize: theme.typography.h3.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.s,
    },
    forecastRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 4,
    },
    forecastLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.textSecondary,
    },
    forecastAmount: {
      fontSize: theme.typography.bodySmall.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    forecastSurplusBar: {
      height: 6,
      borderRadius: 3,
      marginTop: theme.spacing.s,
      overflow: "hidden",
    },
    forecastSurplusFill: {
      height: "100%",
      borderRadius: 3,
    },
    deficitWarning: {
      marginTop: theme.spacing.s,
      padding: theme.spacing.s,
      borderRadius: theme.borderRadius.s,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    deficitWarningText: {
      fontSize: theme.typography.caption.fontSize,
      fontWeight: "600",
      flex: 1,
    },
    settlementProgress: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
      ...theme.shadows.small,
    },
    progressBar: {
      height: 10,
      borderRadius: 5,
      backgroundColor: `${theme.colors.textTertiary}20`,
      marginVertical: theme.spacing.s,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: 5,
    },
    settlementItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: theme.spacing.m,
      borderRadius: 16,
      marginBottom: theme.spacing.s,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
    },
    statusText: {
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    analyticsCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
      ...theme.shadows.small,
    },
    analyticsTitle: {
      fontSize: theme.typography.h3.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.m,
    },
    barContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: theme.spacing.s,
    },
    barLabel: {
      width: 100,
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
    },
    barTrack: {
      flex: 1,
      height: 20,
      borderRadius: 6,
      backgroundColor: `${theme.colors.textTertiary}15`,
      overflow: "hidden",
      flexDirection: "row",
    },
    barFill: {
      height: "100%",
      borderRadius: 6,
    },
    accuracyValue: {
      fontSize: 36,
      fontWeight: "800",
      textAlign: "center",
      marginVertical: theme.spacing.s,
    },
    accuracyLabel: {
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
      textAlign: "center",
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 60,
      paddingHorizontal: theme.spacing.xl,
    },
    emptyText: {
      fontSize: theme.typography.body.fontSize,
      color: theme.colors.textSecondary,
      textAlign: "center",
      marginTop: theme.spacing.m,
    },
    addButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: theme.spacing.m,
      borderRadius: 16,
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: `${theme.colors.primary}50`,
      marginBottom: theme.spacing.s,
    },
    addButtonText: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.primary,
      marginLeft: theme.spacing.s,
    },
    inputCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.m,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}30`,
    },
    inputField: {
      fontSize: theme.typography.body.fontSize,
      color: theme.colors.text,
      borderBottomWidth: 1,
      borderBottomColor: `${theme.colors.textTertiary}30`,
      paddingVertical: theme.spacing.s,
      marginBottom: theme.spacing.s,
    },
    inputActions: {
      flexDirection: "row",
      gap: theme.spacing.s,
    },
    editModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    editModalContent: {
      backgroundColor: theme.colors.modal,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingBottom: 40,
    },
    editModalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: 20,
      textAlign: "center",
    },
    editFieldRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: theme.colors.card,
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginBottom: 16,
    },
    editFieldIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.backgroundSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    editFieldInput: {
      flex: 1,
      fontSize: 16,
      fontWeight: "500",
      color: theme.colors.text,
      padding: 0,
    },
    editActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 8,
    },
    itemActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginLeft: 8,
    },
    simulatorCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}40`,
      ...theme.shadows.small,
    },
    simulatorRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 8,
    },
    simulatorLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.text,
      fontWeight: "500",
      flex: 1,
    },
    simulatorAmount: {
      fontSize: theme.typography.bodySmall.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      minWidth: 70,
      textAlign: "right",
    },
    simulatorStepper: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginLeft: 12,
    },
    stepperBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.backgroundSecondary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    suggestionCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: `${theme.colors.primary}10`,
      borderWidth: 1,
      borderColor: `${theme.colors.primary}30`,
    },
    suggestionTitle: {
      fontSize: 13,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: theme.colors.primary,
      marginBottom: 12,
    },
    suggestionItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginBottom: 8,
    },
    suggestionText: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.text,
      flex: 1,
      lineHeight: 18,
    },
    comparisonCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 2,
      borderColor: `${theme.colors.primary}50`,
      ...theme.shadows.medium,
    },
    comparisonRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 6,
    },
    comparisonLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.textSecondary,
      fontWeight: "500",
    },
    comparisonValue: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
    },
    donutContainer: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
      alignItems: "center",
    },
    donutTitle: {
      fontSize: theme.typography.h3.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.m,
    },
    projectionTable: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: 20,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.border}60`,
    },
    projectionHeader: {
      flexDirection: "row",
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: `${theme.colors.textTertiary}30`,
      marginBottom: 8,
    },
    projectionHeaderText: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    projectionRow: {
      flexDirection: "row",
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: `${theme.colors.textTertiary}15`,
    },
    projectionCell: {
      fontSize: 13,
      fontWeight: "500",
      color: theme.colors.text,
    },
    projectionBarTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: `${theme.colors.textTertiary}20`,
      overflow: "hidden",
      flex: 1,
      marginHorizontal: 8,
    },
    projectionBarFill: {
      height: "100%",
      borderRadius: 3,
    },
  });
