import { StyleSheet } from "react-native";
import type { Theme } from "../theme";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    summaryCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: theme.borderRadius.l,
      backgroundColor: theme.colors.surface,
      ...theme.shadows.medium,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: theme.spacing.xs,
    },
    summaryLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.textSecondary,
    },
    summaryAmount: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: `${theme.colors.textTertiary}40`,
      marginVertical: theme.spacing.s,
    },
    surplusAmount: {
      fontSize: theme.typography.h2.fontSize,
      fontWeight: "700",
    },
    section: {
      marginHorizontal: theme.spacing.m,
      marginBottom: theme.spacing.m,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: theme.spacing.s,
      paddingHorizontal: theme.spacing.s,
    },
    sectionTitle: {
      fontSize: theme.typography.bodySmall.fontSize,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      color: theme.colors.textSecondary,
    },
    sectionTotal: {
      fontSize: theme.typography.bodySmall.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    itemCard: {
      flexDirection: "row",
      alignItems: "center",
      padding: theme.spacing.m,
      borderRadius: theme.borderRadius.m,
      marginBottom: theme.spacing.s,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.textTertiary}20`,
    },
    itemIcon: {
      width: 40,
      height: 40,
      borderRadius: theme.borderRadius.m,
      alignItems: "center",
      justifyContent: "center",
      marginRight: theme.spacing.m,
    },
    itemInfo: {
      flex: 1,
    },
    itemLabel: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    itemSubtext: {
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
      marginTop: 2,
    },
    itemAmount: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "700",
    },
    forecastCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: theme.borderRadius.l,
      backgroundColor: theme.colors.surface,
      ...theme.shadows.small,
    },
    forecastMonth: {
      fontSize: theme.typography.h3.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.s,
    },
    forecastRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 3,
    },
    forecastLabel: {
      fontSize: theme.typography.bodySmall.fontSize,
      color: theme.colors.textSecondary,
    },
    forecastAmount: {
      fontSize: theme.typography.bodySmall.fontSize,
      fontWeight: "600",
      color: theme.colors.text,
    },
    settlementProgress: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: theme.borderRadius.l,
      backgroundColor: theme.colors.surface,
      ...theme.shadows.small,
    },
    progressBar: {
      height: 8,
      borderRadius: 4,
      backgroundColor: `${theme.colors.textTertiary}20`,
      marginVertical: theme.spacing.s,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: 4,
    },
    settlementItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: theme.spacing.m,
      borderRadius: theme.borderRadius.m,
      marginBottom: theme.spacing.s,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: `${theme.colors.textTertiary}20`,
    },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: theme.borderRadius.s,
    },
    statusText: {
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    analyticsCard: {
      margin: theme.spacing.m,
      padding: theme.spacing.l,
      borderRadius: theme.borderRadius.l,
      backgroundColor: theme.colors.surface,
      ...theme.shadows.small,
    },
    analyticsTitle: {
      fontSize: theme.typography.h3.fontSize,
      fontWeight: "700",
      color: theme.colors.text,
      marginBottom: theme.spacing.m,
    },
    barContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: theme.spacing.s,
    },
    barLabel: {
      width: 100,
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
    },
    barTrack: {
      flex: 1,
      height: 20,
      borderRadius: 4,
      backgroundColor: `${theme.colors.textTertiary}15`,
      overflow: "hidden",
      flexDirection: "row",
    },
    barFill: {
      height: "100%",
      borderRadius: 4,
    },
    accuracyValue: {
      fontSize: 36,
      fontWeight: "800",
      textAlign: "center",
      marginVertical: theme.spacing.s,
    },
    accuracyLabel: {
      fontSize: theme.typography.caption.fontSize,
      color: theme.colors.textSecondary,
      textAlign: "center",
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 60,
      paddingHorizontal: theme.spacing.xl,
    },
    emptyText: {
      fontSize: theme.typography.body.fontSize,
      color: theme.colors.textSecondary,
      textAlign: "center",
      marginTop: theme.spacing.m,
    },
    addButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      padding: theme.spacing.m,
      borderRadius: theme.borderRadius.m,
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: `${theme.colors.primary}50`,
      marginBottom: theme.spacing.s,
    },
    addButtonText: {
      fontSize: theme.typography.body.fontSize,
      fontWeight: "600",
      color: theme.colors.primary,
      marginLeft: theme.spacing.s,
    },
  });
