import { StyleSheet } from "react-native";
import { Theme } from "../theme/theme";

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  planCard: {
    marginHorizontal: theme.spacing.l,
    marginTop: theme.spacing.m,
    marginBottom: theme.spacing.s,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: `${theme.colors.primary}25`,
    ...theme.shadows.small,
  },
  planCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: theme.spacing.s,
  },
  planCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  planIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: `${theme.colors.primary}18`,
    alignItems: "center",
    justifyContent: "center",
  },
  planTitle: {
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: "600",
    color: theme.colors.text,
  },
  planSubtitle: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textSecondary,
  },
  planViewLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  planViewText: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.primary,
    fontWeight: "600",
  },
  planRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: theme.spacing.xs,
  },
  planRowLabel: {
    fontSize: theme.typography.bodySmall.fontSize,
    color: theme.colors.textSecondary,
  },
  planRowValue: {
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: "600",
  },
  planDivider: {
    height: 1,
    backgroundColor: `${theme.colors.textTertiary}30`,
    marginVertical: theme.spacing.s,
  },
  planSurplusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  planSurplusAmount: {
    fontSize: theme.typography.body.fontSize,
    fontWeight: "700",
  },
  planSurplusLabel: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textSecondary,
  },
  planBillsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: theme.spacing.s,
    paddingTop: theme.spacing.s,
    borderTopWidth: 1,
    borderTopColor: `${theme.colors.textTertiary}20`,
  },
  planBillsText: {
    fontSize: theme.typography.caption.fontSize,
    color: theme.colors.textSecondary,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.l,
    marginTop: theme.spacing.xl,
    marginBottom: theme.spacing.m,
  },
  sectionTitle: {
    fontSize: theme.typography.h3.fontSize,
    fontWeight: "600",
    color: theme.colors.text,
  },
  sectionAction: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.primary,
  },
  cardScroll: {
    paddingLeft: theme.spacing.l,
  },
  card: {
    width: 200,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginRight: 16,
    gap: 12,
    ...theme.shadows.small,
  },
  cardIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cardBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: theme.colors.backgroundSecondary,
  },
  cardBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.colors.textTertiary,
  },
  cardName: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.text,
  },
  cardSubtext: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginTop: 2,
  },
  cardProgressBg: {
    height: 6,
    width: "100%",
    backgroundColor: theme.colors.backgroundSecondary,
    borderRadius: 3,
    overflow: "hidden",
    marginTop: 8,
  },
  cardProgressFill: {
    height: "100%",
    borderRadius: 3,
  },
  emptyCard: {
    width: 200,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginRight: 16,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.textSecondary,
    textAlign: "center",
  },
  linkCard: {
    marginHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.s,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    ...theme.shadows.small,
  },
  linkCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  linkCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: `${theme.colors.primary}15`,
    alignItems: "center",
    justifyContent: "center",
  },
  linkCardText: {
    fontSize: 15,
    fontWeight: "600",
    color: theme.colors.text,
  },
  linkCardSubtext: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  netWorthCard: {
    marginHorizontal: theme.spacing.l,
    marginBottom: theme.spacing.m,
    padding: theme.spacing.m,
    borderRadius: theme.borderRadius.l,
    backgroundColor: theme.colors.card,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.small,
  },
  netWorthTitle: {
    fontSize: theme.typography.bodySmall.fontSize,
    fontWeight: "600",
    color: theme.colors.textSecondary,
    marginBottom: theme.spacing.xs,
  },
  netWorthAmount: {
    fontSize: 28,
    fontWeight: "800",
    color: theme.colors.text,
  },
  netWorthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: theme.spacing.s,
  },
  netWorthItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  netWorthItemText: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.colors.textSecondary,
  },
});