import { Platform, StyleSheet } from "react-native";

export const createStyles = (theme: any, isDark: boolean) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    keyboardView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    headerSection: {
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        paddingTop: Platform.OS === "ios" ? 20 : 40,
        paddingBottom: 24,
        paddingHorizontal: 24,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: isDark ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.05)",
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: theme.text,
    },
    formSection: {
        paddingHorizontal: 24,
        paddingBottom: 40,
        gap: 32,
    },
    inputContainer: {
        gap: 12,
    },
    label: {
        fontSize: 14,
        fontWeight: "600",
        color: isDark ? "#94A3B8" : "#64748B",
        marginLeft: 4,
    },
    inputWrapper: {
        position: "relative",
        width: "100%",
    },
    inputIcon: {
        position: "absolute",
        left: 16,
        top: 18,
        zIndex: 10,
    },
    input: {
        height: 60,
        borderRadius: 16,
        borderWidth: 1,
        paddingLeft: 48,
        paddingRight: 16,
        fontSize: 16,
        backgroundColor: theme.surface,
        borderColor: isDark ? "rgba(255,255,255,0.05)" : "#E2E8F0",
        color: theme.text,
        textAlign: 'left',
        textAlignVertical: 'center',
    },
    inputError: {
        borderColor: theme.error || "#EF4444",
    },
    grid: {
        flexDirection: "column",
        gap: 12,
    },
    typeCard: {
        width: "100%",
        padding: 16,
        borderRadius: 20,
        backgroundColor: theme.surface,
        borderWidth: 1,
        borderColor: isDark ? "rgba(255,255,255,0.05)" : "#E2E8F0",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: 16,
        position: "relative",
    },
    typeCardSelected: {
        borderColor: theme.primary,
        backgroundColor: isDark ? "rgba(19, 127, 236, 0.05)" : "rgba(19, 127, 236, 0.05)",
    },
    typeIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
    },
    typeLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: theme.text,
        textAlign: "left",
        flex: 1,
    },
    checkCircle: {
        marginLeft: "auto",
    },
    balanceCard: {
        backgroundColor: theme.surface,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: isDark ? "rgba(255,255,255,0.05)" : "#E2E8F0",
        padding: 32,
        alignItems: "center",
        gap: 8,
    },
    currencyBadge: {
        backgroundColor: isDark ? "rgba(19, 127, 236, 0.1)" : "rgba(19, 127, 236, 0.1)",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        marginBottom: 8,
    },
    currencyText: {
        fontSize: 12,
        fontWeight: "800",
        color: theme.primary,
        letterSpacing: 1,
    },
    balanceInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    currencySymbol: {
        fontSize: 48,
        fontWeight: "700",
        color: theme.text,
        marginRight: 4,
    },
    balanceInput: {
        fontSize: 48,
        fontWeight: "700",
        color: theme.text,
        minWidth: 100,
        textAlign: "center",
        padding: 0,
    },
    helperText: {
        fontSize: 12,
        color: isDark ? "#64748B" : "#94A3B8",
        marginTop: 8,
    },
    footer: {
        padding: 24,
        paddingBottom: Platform.OS === "ios" ? 32 : 24,
        borderTopWidth: 1,
        borderTopColor: isDark ? "rgba(255,255,255,0.05)" : "#E2E8F0",
    },
    createButton: {
        backgroundColor: theme.primary,
        height: 64,
        borderRadius: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
    createButtonText: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "700",
    },
    errorText: {
        fontSize: 12,
        color: theme.error || "#EF4444",
        marginTop: 4,
        marginLeft: 4,
    },
});
